/*
 * ports_pins_config.c
 *
 *  Created on: Oct 26, 2024
 *      Author: jacob
 */

#include "ports_pins_config.h"

const int bulb0_PORTS[4] = { GPIO_PORTK_BASE, GPIO_PORTE_BASE, GPIO_PORTE_BASE,
	GPIO_PORTK_BASE };
const int bulb0_PINS[4] = { GPIO_PIN_1, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_0 };

const int bulb1_PORTS[4] = { GPIO_PORTD_BASE, GPIO_PORTK_BASE, GPIO_PORTK_BASE,
	GPIO_PORTD_BASE };
const int bulb1_PINS[4] = { GPIO_PIN_4, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_5 };

const int bulb2_PORTS[4] = { GPIO_PORTD_BASE, GPIO_PORTD_BASE, GPIO_PORTD_BASE,
	GPIO_PORTD_BASE };
const int bulb2_PINS[4] = { GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_1, GPIO_PIN_0 };

const int bulb3_PORTS[4] = { GPIO_PORTF_BASE, GPIO_PORTL_BASE, GPIO_PORTB_BASE,
	GPIO_PORTB_BASE };
const int bulb3_PINS[4] = { GPIO_PIN_2, GPIO_PIN_4, GPIO_PIN_2, GPIO_PIN_3 };

const int bulb4_PORTS[4] = { GPIO_PORTJ_BASE, GPIO_PORTP_BASE, GPIO_PORTP_BASE,
	GPIO_PORTP_BASE };
const int bulb4_PINS[4] = { GPIO_PIN_0, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5 };

const int bulb5_PORTS[4] = { GPIO_PORTM_BASE, GPIO_PORTJ_BASE, GPIO_PORTM_BASE,
	GPIO_PORTM_BASE };
const int bulb5_PINS[4] = { GPIO_PIN_5, GPIO_PIN_1, GPIO_PIN_7, GPIO_PIN_6 };

const int bulb_PORTS[6][4] = { { GPIO_PORTK_BASE, GPIO_PORTE_BASE, GPIO_PORTE_BASE, GPIO_PORTK_BASE },
	{ GPIO_PORTD_BASE, GPIO_PORTK_BASE, GPIO_PORTK_BASE, GPIO_PORTD_BASE },
	{ GPIO_PORTD_BASE, GPIO_PORTD_BASE, GPIO_PORTD_BASE, GPIO_PORTD_BASE },
	{ GPIO_PORTF_BASE, GPIO_PORTL_BASE, GPIO_PORTB_BASE, GPIO_PORTB_BASE },
	{ GPIO_PORTJ_BASE, GPIO_PORTP_BASE, GPIO_PORTP_BASE, GPIO_PORTP_BASE },
	{ GPIO_PORTM_BASE, GPIO_PORTJ_BASE, GPIO_PORTM_BASE, GPIO_PORTM_BASE }, };

const int bulb_PINS[6][4] = { { GPIO_PIN_1, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_0 },
		{ GPIO_PIN_4, GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_5 },
		{ GPIO_PIN_2, GPIO_PIN_3, GPIO_PIN_1, GPIO_PIN_0 },
		{ GPIO_PIN_2, GPIO_PIN_4, GPIO_PIN_2, GPIO_PIN_3 },
		{ GPIO_PIN_0, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5 },
		{ GPIO_PIN_5, GPIO_PIN_1, GPIO_PIN_7, GPIO_PIN_6 } };
